CREATE TABLE dept_TCL
AS 
SELECT * FROM dept;

SELECT * FROM dept_TCL;

desc dept;
desc dept_TCL;

SELECT * FROM dept_TCL;
-- 삽입업무 수행
INSERT INTO dept_TCL VALUES (50, 'DATABASE', 'SEOUL');
INSERT INTO dept_TCL VALUES (60, 'INFO', 'BUSAN');

commit;

INSERT INTO dept_TCL VALUES (70, 'DEV', 'INCHON');

CREATE TABLE emp_TCL
AS
SELECT * FROM emp;

UPDATE dept_TCL SET dname = 'DEVELOP';

commit;

SELECT * FROM dept_TCL;

UPDATE dept_TCL SET dname = 'HR' WHERE deptno=80;

SAVEPOINT sql;

INSERT INTO dept_TCL VALUES (90, 'HR2', 'TEXAS');

SAVEPOINT sp2;

UPDATE dept_TCL SET dname = 'HUMAN RESOURCE' WHERE deptno = 80;

SELECT * FROM dept_TCL ORDER BY deptno;

ROLLBACK TO sql;

SELECT * FROM dept_TCL ORDER BY deptno;


--------------------------------------------------------------------------------
CREATE TABLE account(
    acid NUMBER PRIMARY KEY,
    balance NUMBER NOT NULL
);

INSERT INTO account VALUES(1, 1000);
INSERT INTO account VALUES(2, 500);

COMMIT;

SELECT * FROM account;
--------------------------------------------------------------------------------
-- 시퀀스
-- 자동으로 증가(또는 감소)하는 숫자를 생성해 주는 객체
-- PK값 자동 생성에 주로 사용
-- INSERT 할 때마다 중복 없는 숫자를 안전하게 만들어줌.

-- 시퀀스 생성
-- CREATE SEQUENCE 시퀀스면;

-- 옵션 추가
CREATE SEQUENCE seq_board
START WITH 1     -- 시작값
INCREMENT BY 1   -- 증가값
NOCACHE          -- 캐시 사용 안함
NOCYCLE;         -- 재사용 안함

-- 다음 값 생성
SELECT seq_board.NEXTVAL FROM dual;

-- 현재 값 확인
SELECT seq_board.CURRVAL FROM dual;
-- (같은 세션에서 NEXTVAL을 한 번이라도 실행한 후에만 사용 가능)

-- 시퀀스 삭제
DROP SEQUENCE seq_board;


CREATE TABLE sequenceTable(
    seqnum VARCHAR2(20) PRIMARY KEY,
    seqcol VARCHAR2(20) NOT NULL
);

INSERT INTO sequenceTable (seqnum, seqcol) VALUES('p' || seq_board.NEXTVAL, 'Cherta');
INSERT INTO sequenceTable (seqnum, seqcol) VALUES('p' || seq_board.NEXTVAL, 'Lumina');
INSERT INTO sequenceTable (seqnum, seqcol) VALUES('p' || seq_board.NEXTVAL, 'Max');

SELECT * FROM sequenceTable;

delete sequenceTable WHERE seqnum = 3;
DROP TABLE sequenceTable;


--------------------------------------------------------------------------------
CREATE TABLE emptbl(
    empno NUMBER PRIMARY KEY,
    ename VARCHAR2(20),
    sal NUMBER
);

CREATE TABLE emp_log(
log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
empno NUMBER,
action VARCHAR2(10),
log_date DATE
);
drop table emp_log;

-- drop trigger trg_emptbl_insert;
CREATE OR REPLACE TRIGGER trg_emptbl_insert
AFTER INSERT ON emptbl
FOR EACH ROW
BEGIN
    INSERT INTO emp_log(empno, action, log_date)
    VALUES(:NEW.empno, 'INSERT', SYSDATE);
END;
/
INSERT INTO emptbl VALUES (1003, 'smith3', 5000);

SELECT * FROM emp_log;

ROLLBACK;


CREATE OR REPLACE TRIGGER trg_emptbl_audit
AFTER INSERT OR UPDATE OR DELETE ON emptbl
FOR EACH ROW
BEGIN
    IF INSERTING then
        INSERT INTO emp_log VALUES (DEFAULT, :NEW.empno, 'INSERT', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO emp_log VALUES (DEFAULT, :NEW.empno, 'UPDATE', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO emp_log VALUES (DEFAULT, :OLD.empno, 'DELETE', SYSDATE);
    END IF;
END;
/
ALTER TRIGGER trg_emptbl_insert enable;
ALTER TRIGGER trg_emptbl_insert disable;

CREATE OR REPLACE TRIGGER trg_emp_sal_update
AFTER UPDATE OF sal ON emp
FOR EACH ROW
BEGIN
    INSERT INTO emp_sal_log(
        empno,
        old_sal,
        new_sal,
        log_date
    )
    VALUES(
        :OLD.empno,
        :OLD.sal,
        :NEW.SAL,
        SYSDATE
    );
END;
/


SELECT * FROM user_sys_privs WHERE privilege = 'CREATE VIEW';

CREATE VIEW v_emp_dept
as
SELECT emp.empno, emp.ename, dept.dname
FROM emp
JOIN dept
on emp.deptno = dept.deptno;

SELECT * FROM v_emp_dept;

SELECT * FROM emptbl;


select * from student;

SELECT stu_name, stu_dept FROM student WHERE stu_name = '심%' AND stu_dept = '전기전자';

SELECT * FROM dept;
SELECT * FROM emp;
