/*  주문목록조회 페이지에 사용할 SQL문
-----------------------------------------------------------------------------------------------------------*/
SELECT
    TSHOP.SHOPNO AS SHOPNO,
    TSHOP.SHOPNAME AS SHOPNAME,
    SUBSTR(TORD.ORDERNO,1,4) || '-' || SUBSTR(TORD.ORDERNO,5,4) AS ORDERNO,
    TO_CHAR(TO_DATE(TORD.ORDERDATE, 'YYYYMMDD'), 'YYYY-MM-DD') AS ORDERDATE,
    TPRD.PCODE AS PCODE,
    TPRD.PNAME AS PNAME,
    TORD.AMOUNT AS AMOUNT,
    TO_CHAR(TPRD.COST, 'FM999,999') AS COST,
    TO_CHAR(TORD.AMOUNT * TPRD.COST, 'FM999,999') AS TOTAL_PRICE,
    TO_CHAR(TORD.AMOUNT * TPRD.COST * (100 - TSHOP.DISCOUNT) / 100, 'FM999,999,999') AS DISCOUNT_PRICE
FROM TBL_ORDER_202101 TORD
JOIN TBL_SHOP_202101 TSHOP ON TORD.SHOPNO = TSHOP.SHOPNO
JOIN TBL_PRODUCT_202101 TPRD ON TORD.PCODE = TPRD.PCODE
ORDER BY TORD.ORDERNO ASC;

/*  점포별 주문현황 페이지에 사용할 SQL문
-----------------------------------------------------------------------------------------------------------*/
SELECT TSHOP.SHOPNO AS SHOPNO, TPRD.PCODE AS PCODE, TPRD.PNAME AS PNAME, SUM(TORD.AMOUNT) AS TOTAL_AMOUNT
FROM tbl_order_202101 TORD
JOIN tbl_shop_202101 TSHOP ON TORD.shopno = TSHOP.shopno
JOIN tbl_product_202101 TPRD ON TORD.pcode = TPRD.pcode
GROUP BY TPRD.pname, TPRD.pcode, TSHOP.shopno
ORDER BY TSHOP.SHOPNO ASC;
